/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.neu.aedproject.rranjolkar.ui;

import Business.DB4OUtil.DB4OUtil;
import edu.neu.aedproject.rranjolkar.Ecosystem;
import edu.neu.aedproject.rranjolkar.services.LoginService;
import java.awt.BorderLayout;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author Rutika Ranjolkar
 */
public class GenericJFrame extends javax.swing.JFrame {

    private static GenericJFrame instance;

    private final Ecosystem ecosystem;

    public static GenericJFrame getInstance() {
        if (instance == null) {
            instance = new GenericJFrame();
            instance.setExtendedState(JFrame.MAXIMIZED_BOTH);
        }
        return instance;
    }

    public void populate(JPanel topPanel, JPanel bottomPanel) {
        pnlTop.removeAll();
        pnlBottom.removeAll();
        pnlTop.add(topPanel);
        pnlBottom.add(bottomPanel);
        pnlTop.revalidate();
        pnlTop.repaint();
        pnlBottom.revalidate();
        pnlBottom.repaint();
        this.repaint();
    }

    /**
     * Creates new form GenericJFrame
     */
    private GenericJFrame() {
        initComponents();

        pnlTop.setLayout(new BorderLayout());

        ecosystem = DB4OUtil.getInstance().retrieveSystem();
    }

    public void logout() {
        LoginService.getInstance().logout();
        save();
    }

    public Ecosystem getEcosystem() {
        return ecosystem;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTop = new javax.swing.JPanel();
        pnlBottom = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlTop.setBackground(new java.awt.Color(0, 0, 102));

        javax.swing.GroupLayout pnlTopLayout = new javax.swing.GroupLayout(pnlTop);
        pnlTop.setLayout(pnlTopLayout);
        pnlTopLayout.setHorizontalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        pnlTopLayout.setVerticalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(pnlTop, java.awt.BorderLayout.PAGE_START);

        pnlBottom.setBackground(new java.awt.Color(255, 255, 255));
        pnlBottom.setLayout(new java.awt.GridBagLayout());
        getContentPane().add(pnlBottom, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnlBottom;
    private javax.swing.JPanel pnlTop;
    // End of variables declaration//GEN-END:variables

    void save() {
        DB4OUtil.getInstance().storeSystem(ecosystem);
    }
}
