/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.neu.aedproject.rranjolkar.ui;

import Business.DB4OUtil.DB4OUtil;

/**
 *
 * @author Rutika Ranjolkar
 */
public class SecurityManagerTopPanel extends javax.swing.JPanel {

    /**
     * Creates new form PortfolioManagerTopPanel
     */
    public SecurityManagerTopPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnWorkQueue = new javax.swing.JButton();
        btnMyWorkQueue = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnAuditTrails = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 102));

        btnWorkQueue.setText("Work Queue");
        btnWorkQueue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWorkQueueActionPerformed(evt);
            }
        });

        btnMyWorkQueue.setText("My Work Queue");
        btnMyWorkQueue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMyWorkQueueActionPerformed(evt);
            }
        });

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnAuditTrails.setText("Audit Trails");
        btnAuditTrails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAuditTrailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btnWorkQueue, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMyWorkQueue, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAuditTrails, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnWorkQueue, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMyWorkQueue, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAuditTrails, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnWorkQueueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWorkQueueActionPerformed
        GenericJFrame.getInstance().populate(this, new SecurityEscalatedWorkQueuePanel());
    }//GEN-LAST:event_btnWorkQueueActionPerformed

    private void btnMyWorkQueueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMyWorkQueueActionPerformed
        GenericJFrame.getInstance().populate(this, new SecurityAnalystWorkQueuePanel());
    }//GEN-LAST:event_btnMyWorkQueueActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        GenericJFrame.getInstance().logout();
        GenericJFrame.getInstance().populate(new WelcomeJPanel(), new LoginJPanel());
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnAuditTrailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAuditTrailsActionPerformed
        GenericJFrame.getInstance().populate(new SecurityManagerTopPanel(), new SecurityManagerAuditTrailPanel());
    }//GEN-LAST:event_btnAuditTrailsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAuditTrails;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMyWorkQueue;
    private javax.swing.JButton btnWorkQueue;
    // End of variables declaration//GEN-END:variables
}
