/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.neu.aedproject.rranjolkar.ui;

import edu.neu.aedproject.rranjolkar.AuditItem;
import edu.neu.aedproject.rranjolkar.UserAccount;
import edu.neu.aedproject.rranjolkar.security.VacationLoginBlockedWorkRequest;
import edu.neu.aedproject.rranjolkar.services.LoginService;
import edu.neu.aedproject.rranjolkar.trading.util.CommonUtils;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Rutika Ranjolkar
 */
public class VacationLoginBlockedPanel extends javax.swing.JPanel {

    private final VacationLoginBlockedWorkRequest request;
    private final ResettablePanel parentPanel;

    /**
     * Creates new form UserAccountBlockedPanel
     */
    public VacationLoginBlockedPanel(VacationLoginBlockedWorkRequest request, ResettablePanel parentPanel) {
        initComponents();

        this.request = request;
        this.parentPanel = parentPanel;

        /**
         * Populate fields *
         */
        lblUserRiskNumber.setText(request.getSender().getSecurityRiskNumber() + "");
        lblVacationStart.setText(request.getSender().getVacationStartDate().toString());
        lblVacationEnd.setText(request.getSender().getVacationEndDate().toString());
        lblVacationDetails.setText(request.getSender().getVacationDetails());
        if (request.isEscalated()) {
            lblEscalationNotes.setText(request.getEscalationNotes());
            btnEscalate.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblUserRiskNumber = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblVacationStart = new javax.swing.JLabel();
        lblVacationEnd = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblVacationDetails = new javax.swing.JLabel();
        btnUnblock = new javax.swing.JButton();
        btnEscalate = new javax.swing.JButton();
        lblEscalationNotes = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("User Risk Number:");

        lblUserRiskNumber.setText(".");

        jLabel2.setText("Vacation Start Date:");

        jLabel3.setText("Vacation End Date:");

        lblVacationStart.setText(".");

        lblVacationEnd.setText(".");

        jLabel4.setText("Vacation Details:");

        lblVacationDetails.setBackground(new java.awt.Color(255, 255, 255));
        lblVacationDetails.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblVacationDetails.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblVacationDetails.setOpaque(true);

        btnUnblock.setText("Unblock Account");
        btnUnblock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnblockActionPerformed(evt);
            }
        });

        btnEscalate.setText("Escalate to Security Mgmt");
        btnEscalate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEscalateActionPerformed(evt);
            }
        });

        lblEscalationNotes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblEscalationNotes.setForeground(new java.awt.Color(255, 51, 51));
        lblEscalationNotes.setText("                      ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEscalate, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUnblock, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVacationDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblUserRiskNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblVacationStart, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(50, 50, 50)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblVacationEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(lblEscalationNotes))
                        .addGap(0, 3, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(lblEscalationNotes)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblUserRiskNumber))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblVacationStart)
                    .addComponent(jLabel3)
                    .addComponent(lblVacationEnd))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblVacationDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEscalate)
                    .addComponent(btnUnblock))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUnblockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnblockActionPerformed
        request.getSender().backFromVacation();
        request.resolve();
        CommonUtils.showMessage("User account unblocked successfully!");
        UserAccount unblocker = LoginService.getInstance().getCurrentAccount();
        unblocker.getAuditTrail().add(
                new AuditItem(new Date(),
                        "Unblocked user account: " + request.getSender()
                )
        );
        request.getSender().getAuditTrail().add(new AuditItem(new Date(), "Account was unblocked by: " + unblocker));
        parentPanel.reset();
    }//GEN-LAST:event_btnUnblockActionPerformed

    private void btnEscalateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEscalateActionPerformed
        String escalationNotes = JOptionPane.showInputDialog("Please enter escalation notes.");
        request.setEscalationNotes(escalationNotes);
        request.setEscalated(true);
        request.setReceiver(null);
        LoginService.getInstance().getCurrentAccount().getAuditTrail().add(
                new AuditItem(new Date(),
                        "Escalated vacation login blocked request: " + request.getMessage()
                        + " for reason: " + escalationNotes
                )
        );
        parentPanel.reset();
    }//GEN-LAST:event_btnEscalateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEscalate;
    private javax.swing.JButton btnUnblock;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblEscalationNotes;
    private javax.swing.JLabel lblUserRiskNumber;
    private javax.swing.JLabel lblVacationDetails;
    private javax.swing.JLabel lblVacationEnd;
    private javax.swing.JLabel lblVacationStart;
    // End of variables declaration//GEN-END:variables
}
